[package]
name = "rust_ffi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
flutter_rust_bridge = "=1.72.2"

[build-dependencies]
flutter_rust_bridge_codegen = "=1.72.2"