project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true

files:
  - source: /l10n_arb/intl_zh_CN.arb
    translation: /l10n_arb/intl_%locale_with_underscore%.arb
