targets:
  $default:
    builders:
      drift_dev:
        options:
          databases:
            main_database: lib/src/database.dart
            log_database: lib/src/log_database/log_database.dart