name: build

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Check
        run: |
          flutter pub get
          dart fix
          dart format .
          git diff --exit-code
          if [ $? -eq 0 ]; then
            echo "No formatting changes detected"
          else
            echo "Formatting changes detected. Run `make format` to fix it."
            exit 1
          fi

  build-windows:
    runs-on: windows-latest
    needs: format-check
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Build
        run: |
          flutter config --enable-windows-desktop
          flutter build windows

  build-web:
    runs-on: ubuntu-latest
    needs: format-check
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Build
        run: |
          flutter pub get
          flutter build web

  build-android:
    runs-on: ubuntu-latest
    needs: format-check
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Build
        run: |
          flutter pub get
          flutter build apk
