name: PR check

on:
  pull_request:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Check
        run: |
          flutter pub get
          dart fix
          dart format .
          git diff --exit-code
          if [ $? -eq 0 ]; then
            echo "No formatting changes detected"
          else
            echo "Formatting changes detected. Run `make format` to fix it."
            exit 1
          fi