name: build release file

on:
  release:
    types: [ released ]

  workflow_dispatch:

env:
  APP_NAME: Waiter

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Build
        run: |
          flutter config --enable-windows-desktop
          flutter build windows
          Compress-Archive -Path .\build\windows\runner\Release\* -DestinationPath ${{ env.APP_NAME }}-windows.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{ env.APP_NAME }}-windows.zip

      - uses: actions/upload-artifact@v3
        with:
          name: windows
          path: ${{ env.APP_NAME }}-windows.zip

  build-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Build
        run: |
          flutter pub get
          flutter build web
          tar -zcvf ${{ env.APP_NAME }}-web.tar.gz ./build/web/*

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{ env.APP_NAME }}-web.tar.gz

      - uses: actions/upload-artifact@v3
        with:
          name: web
          path: ${{ env.APP_NAME }}-web.tar.gz

  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Build
        run: |
          flutter pub get
          flutter build apk
          mv ./build/app/outputs/flutter-apk/app-release.apk ${{ env.APP_NAME }}.apk
          mv ./build/app/outputs/flutter-apk/app-release.apk.sha1 ${{ env.APP_NAME }}.apk.sha1

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{ env.APP_NAME }}.apk
            ${{ env.APP_NAME }}.apk.sha1

      - uses: actions/upload-artifact@v3
        with:
          name: android
          path: ${{ env.APP_NAME }}.apk
